<?php
$CONFIG = array (
  'passwordsalt' => 'g2ovJr/qkpPLKPnqZZd8ntiDqTfJyJ',
  'secret' => 'QD8Q6iCu/Bc5ApQ40bPNcooy+HuDPFm4oFSosKhAvv69M3Ee',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'next.cloudoffice.co.za',
  ),
  'datadirectory' => '/var/nc-data',
  'dbtype' => 'pgsql',
  'version' => '20.0.2.2',
  'overwrite.cli.url' => 'https://next.cloudoffice.co.za',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'NkDqyrRgW42yEW7McdU8qtPcecKvlwRH',
  'installed' => true,
  'instanceid' => 'oceuw3qdwbz7',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => '0',
    'timeout' => '0.0',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'enable_previews' => 'true',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\Movie',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
  ),
  'preview_max_x' => '1024',
  'preview_max_y' => '768',
  'preview_max_scale_factor' => '1',
  'auth.bruteforce.protection.enabled' => 'true',
  'trashbin_retention_obligation' => 'auto,7',
  'skeletondirectory' => '',
  'defaultapp' => 'file',
  'activity_expire_days' => '14',
  'integrity.check.disabled' => 'false',
  'updater.release.channel' => 'stable',
);